### ISSUE TITLE
Entity id already exists

### ISSUE THREAD

**Issue by wellsy57** [safepay/sensor.fronius#33]
There is an issue with the integration which does not stop the integration working at all but it continues to raise the same errors and warning for a while now over all of releases I have tested since 0.107.7.

I am now testing in 0.110.1 and these are the errors and warnings which persist:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:436
Integration: Sensor (documentation, issues)
First occurred: 10:58:15 PM (9 occurrences)
Last logged: 10:58:15 PM


Entity id already exists - ignoring: sensor.fronius_ac_current. Platform fronius_inverter does not generate unique IDs
Entity id already exists - ignoring: sensor.fronius_ac_voltage. Platform fronius_inverter does not generate unique IDs
Entity id already exists - ignoring: sensor.fronius_ac_frequency. Platform fronius_inverter does not generate unique IDs
Entity id already exists - ignoring: sensor.fronius_dc_current. Platform fronius_inverter does not generate unique IDs
Entity id already exists - ignoring: sensor.fronius_dc_voltage. Platform fronius_inverter does not generate unique IDs
```

I am using this environment:

```

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Core on Docker
os_name | Linux
os_version | 4.2.8
python_version | 3.7.7
timezone | Australia/Brisbane
version | 0.110.1
virtualenv | false
```

Cheers for building such a fantastic integration!

**Comment by nilrog** [comment]
Never seen this before. How does your config look like for `fronius_inverter`?

**Comment by wellsy57** [comment]
Yeah I thought it strange. Presently have this which was giving no errors or warnings up until 0.107.7

Current config:

```
  - platform: fronius_inverter
    ip_address: 192.168.1.211
    power_units: W
    units: kWh    
    monitored_conditions:
      - ac_power
      - day_energy
      - year_energy
      - total_energy
      - ac_current
      - ac_voltage
      - ac_frequency
      - dc_current
      - dc_voltage

  - platform: fronius_inverter
    ip_address: 192.168.1.211
    powerflow: True
    smartmeter: True
#    smartmeter_device_id: 240.453036
    power_units: W
    units: kWh

  - platform: integration
    source: sensor.fronius_grid_usage
    name: fronius_grid_usage_integration
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.fronius_house_load
    name: fronius_house_load_integration
    unit_prefix: k
    round: 2    

```
