### ISSUE TITLE
Not receiving data

### ISSUE THREAD

**Issue by sweebee** [safepay/sensor.fronius#54]
I tried to add this integration, but I get no data. It works fine with the native integration.

```
- platform: fronius_inverter
  ip_address: 192.168.1.176
  name: fronius

- platform: fronius
  resource: http://192.168.1.176
  monitored_conditions:
  - sensor_type: inverter
```

The log tells me:
```
Failed to update: invalid response received
```
