### ISSUE TITLE
Adding support for 2020.8 Energy dashboard?

### ISSUE THREAD

**Issue by Eonsim** [safepay/sensor.fronius#55]
Has any one got time to add support for the new energy dashboard?
I think all that's needed is to add support for the new statistics framework  by adding to each sensor sensor a state_class that is set to measurement.

**Comment by d3wy** [comment]
I'm working on it presently with no idea what I'm doing. It's (for me) not as straightforward as it seems but I'll keep trying.

**Comment by Eonsim** [comment]
I'm also looking at the code, but not exactly clear how to introduce the state_class to the sensor.

**Comment by d3wy** [comment]
I've tried using entity customization just to add state_class as per https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics to the day_energy sensor without any change/luck.

I've also tried adding this to the plugin:

`    @property
    def state_class(self):
        return measurement`

Without luck

**Comment by Eonsim** [comment]
Apparently a last reset attribute needs to be assigned as well.

    attribute_templates:
      last_reset: '1970-01-01T00:00:00+00:00'
      state_class: 'measurement'

**Comment by colwilliamsnz** [comment]
Awesome effort, thank you! As an interim workaround you could feed the power sensor values into an HA "integration" sensor and then into "utility" sensors...at which point the required attributes are set. Or use "customize.yaml" and add the attributes there.

**Comment by Eonsim** [comment]
I have a rough work around using utility sensors + template sensors, but it's not working reliably:

See below:

 - platform: template
   sensors:
     energy_used:
       value_template: '{{states(grid_consumed_energy_day)}}'
       unit_of_measurement: kWh
       device_class: energy
       attribute_templates:
         state_class: 'measurement'
         last_reset: '1970-01-01T00:00:00+00:00'
     energy_sold:
       value_template: '{{states(grid_sold_energy_day)}}'
       unit_of_measurement: kWh
       device_class: energy
       attribute_templates:
         state_class: 'measurement'
         last_reset: '1970-01-01T00:00:00+00:00'
     energy_gen:
       value_template: '{{states(pv_gen_energy_daily)}}'
       unit_of_measurement: kWh
       device_class: energy
       attribute_templates:
         state_class: 'measurement'
         last_reset: '1970-01-01T00:00:00+00:00'

utility_meter:
  # calculate daily energy consumed from grid (input must be in kWh)
  grid_consumed_energy_day:
    source: sensor.fronius_smartmeter_energy_ac_consumed
    cycle: daily
  # calculate daily energy sold to grid (input must be in kWh)
  grid_sold_energy_day:
    source: sensor.fronius_smartmeter_energy_ac_sold
    cycle: daily
  pv_gen_energy_daily:
    source: sensor.fronius_total_energy
    cycle: daily

**Comment by d3wy** [comment]
I came across similar, only concern so far is that the last reset might cause problems... tomorrow?

**Comment by colwilliamsnz** [comment]
I don't think so...I'm using "daily" energy meters...and as I've had them enabled for a few months now, I have 30 days of history in the new energy panel.

**Comment by nagyrobi** [comment]
https://github.com/home-assistant/core/issues/54047#issuecomment-893305838

**Comment by thehaxxa** [comment]
> I came across similar, only concern so far is that the last reset might cause problems... tomorrow?

I am experiencing issues relating to resets, I'm using the config provided by: @Eonsim 

![image](https://user-images.githubusercontent.com/2765052/128618195-89076b27-c15f-4dc9-9afe-a80ad8ec7aaf.png)

The daily reset (with the sensor adding additional attributes) results in data from the previous day carrying forward. 

----------------------------------

This is the grid consumption output: 
![image](https://user-images.githubusercontent.com/2765052/128618209-e2271358-ba62-4e8f-9a7a-bc81a7152c59.png)

I am curious how @colwilliamsnz over came this problem, could you post your configuration?

I am thinking a solution might be to set an automation to reset the `utility meter` at 11:59:59PM each day.

**Comment by Eonsim** [comment]
@thehaxxa I ended up switching to the main integration as I never quite got this working as well as I wanted it to. It's a pity because this version has much more reasonable names than the main one.

If you want to use the main one the following config works:

```
 - platform: fronius
   resource: http://192.168.xx.xx/
   scan_interval: 10
   monitored_conditions:
   - sensor_type: inverter
   - sensor_type: meter
   - sensor_type: power_flow
```
Then in the energy settings page:
```
Grid consumption: Energy real consumed Fronius Meter 0 http://
Return to grid: Energy real produced Fronius Meter 0 http://
Solar production: Energy total Fronius Inverter 1 http://
```

Note if you live in a country that isn't covered by Solar Forecast (for example NZ), you need to select "Don't forecast" under solar production or you won't get the solar production graph.

**Comment by colwilliamsnz** [comment]
@thehaxxa here you go, I've edited out some extraneous cruft to do with my EV charger etc so hope I got it right...hope this helps :) 

### Template Sensors:

# Convert house power consumption to a positive and round to 0 dp
# Fronius sensor reports as a negative and to 2 decimal places (overkill when reporting watts)
- platform: template
  sensors:
    power_total_consumption:
      friendly_name: Total Consumption
      unit_of_measurement: "W"
      value_template: '{{ (states("sensor.fronius_house_load") | float * -1) | round | int }}'

# The next two template sensors simplify Fronius single sensor value that is positive if consuming
# energy from the grid, and negative if the solar is supplying excess to the grid

# Grid usage
- platform: template
  sensors:
    power_grid_consumption:
      friendly_name: Grid Consumption
      unit_of_measurement: "W"
      value_template: >-
        {% if states('sensor.fronius_grid_usage') | float > 0 %}
          {{ states('sensor.fronius_grid_usage') | round | int }}
        {% else %}
          0
        {% endif %}

# Grid feed-in
- platform: template
  sensors:
    power_grid_feedin:
      friendly_name: Grid Feed-in
      unit_of_measurement: "W"
      value_template: >-
        {% if states('sensor.fronius_grid_usage') | float < 0 %}
          {{ (states('sensor.fronius_grid_usage') | float * -1) | round | int }}
        {% else %}
          0
        {% endif %}

### Integration Sensors:

# Convert house power consumption to energy consumption
- platform: integration
  source: sensor.power_total_consumption
  name: energy_total_consumption
  unit_prefix: k
  unit_time: h
  round: 2
  method: left

# Convert solar power production to energy production
- platform: integration
  source: sensor.fronius_panel_status
  name: energy_solar_production
  unit_prefix: k
  unit_time: h
  round: 2
  method: left

### Utility Sensors:

energy_house_consumption_daily:
  source: sensor.energy_total_consumption
  cycle: daily

energy_solar_production_daily:
  source: sensor.energy_solar_production
  cycle: daily

**Comment by thehaxxa** [comment]
> @thehaxxa here you go, I've edited out some extraneous cruft to do with my EV charger etc so hope I got it right...hope this helps :)
 
 Thanks @colwilliamsnz, that was very well documented and informative. It got me most of the way 🙂
 To expand on it I thought I would include a few more details, specifially how I got Solar production working and cost integration.
 Also I did not use Total Consumption in my Energy Dashboard. 
 
 I should note SignalCO2 works well, hopefully in the future Solcast is added as a forecast provider for AUS/NZ users. 
 
 
 ## Template Sensors:
 ### Convert house power consumption to a positive and round to 0 dp as Fronius sensor reports as a negative and to 2 decimal places (overkill when reporting watts)
 ```
 - platform: template
   sensors:
     power_total_consumption:
       friendly_name: Total Consumption
       unit_of_measurement: "W"
       value_template: '{{ (states("sensor.fronius_house_load") | float * -1) | round | int }}'
 ```
 
 ### The next two template sensors simplify Fronius single sensor value that is positive if consuming energy from the grid, and negative if the solar is supplying excess to the grid
 ```
 - platform: template
   sensors:
     power_grid_consumption:
       friendly_name: Grid Consumption
       unit_of_measurement: "W"
       value_template: >-
         {% if states('sensor.fronius_grid_usage') | float > 0 %}
           {{ states('sensor.fronius_grid_usage') | round | int }}
         {% else %}
           0
         {% endif %}
 
 - platform: template
   sensors:
     power_grid_feedin:
       friendly_name: Grid Feed-in
       unit_of_measurement: "W"
       value_template: >-
         {% if states('sensor.fronius_grid_usage') | float < 0 %}
           {{ (states('sensor.fronius_grid_usage') | float * -1) | round | int }}
         {% else %}
           0
         {% endif %}
 ```
 
 ## Integration Sensors:
 ### Convert house power consumption to energy consumption
 ```
 - platform: integration
   source: sensor.power_total_consumption
   name: energy_total_consumption
   unit_prefix: k
   unit_time: h
   round: 2
   method: left
 ```
 
 ### Convert solar power production to energy production
 ```
 - platform: integration
   source: sensor.fronius_panel_status
   name: energy_solar_production
   unit_prefix: k
   unit_time: h
   round: 2
   method: left
 ```
 ### Convert grid consumption to energy production
 ```
  - platform: integration
    source: sensor.power_grid_consumption
    name: energy_grid_consumption
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
 ```

 ### Convert grid feedin to energy production
 ```
  - platform: integration
    source: sensor.power_grid_feedin
    name: energy_grid_feedin
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
 ```
 
 
 ## Utility Sensors:
 ```
  energy_solar_production_daily:
    name: "PV Generation (Daily)"
    source: sensor.energy_solar_production
    cycle: daily
  energy_grid_consumption_daily:
    name: "Grid Consumption (Daily)"
    source: sensor.energy_grid_consumption
    cycle: daily
  energy_grid_feedin_daily:
    name: "Grid Export (Daily)"
    source: sensor.energy_grid_feedin
    cycle: daily
	
  ## Not used in Energy Dashboard
  energy_house_consumption_daily:
    name: "Total Consumption (Daily)"
    source: sensor.energy_total_consumption
    cycle: daily
 ```
 
 ## Cost Input Number Integration (takes cost in cents i.e. 16.95 -> $0.1695)
 ```
 input_number:
  # Grid Consumption Energy Cost (AUD/kWh) 
  grid_consumption_energy_cost:
    name: 'Grid Consumption Energy Cost'
    mode: box
    min: 0
    max: 1000
    step: 0.001
    unit_of_measurement: "AUD (cents)/kWh"
    icon: mdi:currency-usd
  # Grid Generation Energy Cost (AUD/kWh) 
  grid_generation_energy_cost:
    name: 'Grid Generation Energy Cost'
    mode: box
    min: 0
    max: 1000
    step: 0.001
    unit_of_measurement: "AUD (cents)/kWh"
    icon: mdi:currency-usd
 ```
 ## Converts from cents to Dollars (limitation of input number precision)
 ```
  - platform: template
    sensors:
       energy_consumption_cost_aud:
        icon_template: mdi:currency-usd
        value_template: >
          {{(states('input_number.grid_consumption_energy_cost')|float / 100)|round(4, 'ceil')}}
        unit_of_measurement: 'AUD/kWh'
      energy_generation_cost_aud:
        icon_template: mdi:currency-usd
        value_template: >
          {{(states('input_number.grid_generation_energy_cost')|float / 100)|round(4, 'ceil')}}
        unit_of_measurement: 'AUD/kWh'
 ```
 
 Then the `energy_solar_production_daily`, `energy_grid_consumption_daily` and `energy_grid_feedin_daily`. Are added to the Energy Dashboard. The template cost sensors are used for cost, alternatively a static value can be entered.

**Comment by fondberg** [comment]
I would like it to be in the actual integration rather than messing around with too much template configuration.
In my project we just merged a PR which makes it "automatic". It is quite simple so please have a look: https://github.com/fondberg/easee_hass/pull/131/files

**Comment by sparkydave1981** [comment]
I've added all the required attributes to the sensor.fronius_day_energy entity but it still won't let me add it the the HA Energy system.  Hopefully there is a proper fix possible.
![image](https://user-images.githubusercontent.com/7628509/130021475-1da75735-2e0d-4cc3-ba1c-aa6230da134b.png)

**Comment by safepay** [comment]
@sparkydave1981 
You might be able to add the sensor to a custom template sensor with the addition of
`state_class: measurement`

**Comment by smallsam** [comment]
I believe the sensor name needs to start with "energy_", which seems redundant given the device class but it's what I needed to do for an individual device energy meter.

**Comment by colwilliamsnz** [comment]
> I believe the sensor name needs to start with "energy_", which seems redundant given the device class but it's what I needed to do for an individual device energy meter.

Hi, I can confirm it doesn't need this at all. If you "inject" the missing attributed using customise.yaml it works fine:

```
sensor.fronius_day_energy:
  friendly_name: Fronius Solar Production
  icon: mdi:solar-power
  last_reset: "1970-01-01T00:00:00+00:00"
  device_class: energy
  state_class: measurement
```
