### ISSUE TITLE
fronius gen24 & fronius symo always 0

### ISSUE THREAD

**Issue by RW-7** [safepay/sensor.fronius#58]
Hello, I'm currently trying to integrate and display at least one Fronius.

I don't get any error messages in the log, but the display is 0 no matter where
i have a fronius gen24 with 2 smart meters + 1x fronius symo in the same building.
later I wanted to add a second symo with a smart meter that is external.
But I can't even get one to run

I have now installed release 0.9.6
my config looks like this

```
sensor:
#  - platform: fronius_inverter
#    ip_address: http://192.168.4.96
  - platform: fronius_inverter
    name: Gen24Home
    ip_address: http://192.168.10.96
    powerflow: True
    power_units: kW
    smartmeter: True
utility_meter:
  # calculate daily energy consumed from grid (input must be in kWh)
  grid_consumed_energy_day:
    source: sensor.fronius_smartmeter_energy_ac_consumed
    cycle: daily
  # calculate daily energy sold to grid (input must be in kWh)
  grid_sold_energy_day:
    source: sensor.fronius_smartmeter_energy_ac_sold
    cycle: daily
  energy_solar_production_daily:
   name: "PV Generation (Daily)"
   source: sensor.energy_solar_production
   cycle: daily
  energy_grid_consumption_daily:
   name: "Grid Consumption (Daily)"
   source: sensor.energy_grid_consumption
   cycle: daily
  energy_grid_feedin_daily:
   name: "Grid Export (Daily)"
   source: sensor.energy_grid_feedin
   cycle: daily

 ## Not used in Energy Dashboard
  energy_house_consumption_daily:
   name: "Total Consumption (Daily)"
   source: sensor.energy_total_consumption
   cycle: daily
sensor:
- platform: template
  sensors:
    power_total_consumption:
      friendly_name: Total Consumption
      unit_of_measurement: "W"
      value_template: '{{ (states("sensor.fronius_house_load") | float * -1) | round | int }}'
- platform: template
  sensors:
    power_grid_consumption:
      friendly_name: Grid Consumption
      unit_of_measurement: "W"
      value_template: >-
        {% if states('sensor.fronius_grid_usage') | float > 0 %}
          {{ states('sensor.fronius_grid_usage') | round | int }}
        {% else %}
          0
        {% endif %}
- platform: integration
  source: sensor.power_total_consumption
  name: energy_total_consumption
  unit_prefix: k
  unit_time: h
  round: 2
  method: left
- platform: integration
  source: sensor.fronius_panel_status
  name: energy_solar_production
  unit_prefix: k
  unit_time: h
  round: 2
  method: left
- platform: integration
  source: sensor.power_grid_consumption
  name: energy_grid_consumption
  unit_prefix: k
  unit_time: h
  round: 2
  method: left
- platform: integration
  source: sensor.power_grid_feedin
  name: energy_grid_feedin
  unit_prefix: k
  unit_time: h
  round: 2
  method: left
- platform: template
  sensors:
    power_grid_feedin:
      friendly_name: Grid Feed-in
      unit_of_measurement: "W"
      value_template: >-
        {% if states('sensor.fronius_grid_usage') | float < 0 %}
          {{ (states('sensor.fronius_grid_usage') | float * -1) | round | int }}
        {% else %}
          0
        {% endif %}
- platform: template
  sensors:
     energy_consumption_cost_aud:
      icon_template: mdi:currency-usd
      value_template: >
        {{(states('input_number.grid_consumption_energy_cost')|float / 100)|round(4, 'ceil')}}
      unit_of_measurement: 'EUR/kWh'
     energy_generation_cost_aud:
      icon_template: mdi:currency-usd
      value_template: >
        {{(states('input_number.grid_generation_energy_cost')|float / 100)|round(4, 'ceil')}}
      unit_of_measurement: 'EUR/kWh'

input_number:
 # Grid Consumption Energy Cost (EUR/kWh)
   grid_consumption_energy_cost:
     name: 'Grid Consumption Energy Cost'
     mode: box
     min: 0
     max: 1000
     step: 0.001
     unit_of_measurement: "EUR (cents)/kWh"
     icon: mdi:currency-usd
 # Grid Generation Energy Cost (EUR/kWh)
   grid_generation_energy_cost:
     name: 'Grid Generation Energy Cost'
     mode: box
     min: 0
     max: 1000
     step: 0.001
     unit_of_measurement: "EUR (cents)/kWh"
     icon: mdi:currency-usd

```
