### ISSUE TITLE
Not An Issue!

### ISSUE THREAD

**Issue by cathelest** [safepay/sensor.fronius#6]
Hello Richard,

Many thanks for all your work on the plugin, its great, and thanks for allowing the flowmeter to monitor after sunset, works great now, iv sent you some beer money, have 1 or 2 on me, enjoy!!

Do you have any plans to make a custom card view (like the fronius app) or do you know if theres a way to use the power wheel card https://community.home-assistant.io/t/lovelace-power-wheel-card/82374

Iv tried to use it before but could never work it out properly,

All im missing now is the view!!

Many thanks again for all your hard work, sorry to open an issue but dont know how to contact you otherwise??

Ben (Cathelest)

**Comment by safepay** [comment]
Cheers Ben.Glad I could help and thanks for the beer money.

I'll look in to the power wheel when I have time.

Richard

**Comment by safepay** [comment]
Hi Ben,

Not sure if this looks right on your system, but I configured the basic custom card like this:

```yaml
type: 'custom:power-wheel-card'
solar_power_entity: sensor.fronius_panel_status
grid_power_consumption_entity: sensor.fronius_grid_usage
grid_power_production_entity: sensor.fronius_grid_usage
```

Being sure to add this to the top of your Lovelace config in the Raw Config Editor.
```yaml
resources:
  - type: module
    url: /local/custom_ui/power-wheel-card.js?v=1
```

Note that I put the JS file in ../www/custom_ui/ folder in the HA config folder which is different from the instructions but suits my setup.
