### ISSUE TITLE
Received invalid command: energy/info + Failed to update: connection error

### ISSUE THREAD

**Issue by grekpg** [safepay/sensor.fronius#80]
Hi im new in Home Assistant i try add fronius integration

```
System Health
Version	core-2021.11.5
Installation Type	Home Assistant Supervised
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.9.7
Operating System Family	Linux
Operating System Version	5.11.0-41-generic
CPU Architecture	x86_64
Timezone	UTC
```

i wait many hours but all sensors are empty

"There is no data to show. It can take up to 2 hours for new data to arrive after you configure your energy dashboard."

where can be a problem ?

in logs i see

```
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:89
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:41:17 PM (2 occurrences)
Last logged: 6:41:17 PM

[140562128432624] Received invalid command: energy/info


and 

Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.fronius_inverter.sensor
Source: custom_components/fronius_inverter/sensor.py:375
Integration: fronius_inverter (documentation)
First occurred: 6:47:38 PM (2 occurrences)
Last logged: 6:48:43 PM

Failed to update: connection error

```
fronus is available in 

http://test.my.domain/solar_api/GetAPIVersion.cgi

in this url i have 

```
{
   "APIVersion" : 1,
   "BaseURL" : "/solar_api/v1/",
   "CompatibilityRange" : "1.6-3"
}
```

/config/customize.yaml

```
switch.100051a1df_2:
  assumed_state: true
sensor.fronius_total_energy:
  state_class: measurement
  last_reset: 1970-01-01T00:00:00+00:00
sensor.fronius_smartmeter_energy_ac_consumed:
  state_class: measurement
  last_reset: 1970-01-01T00:00:00+00:00
sensor.fronius_smartmeter_energy_ac_sold:
  state_class: measurement
  last_reset: 1970-01-01T00:00:00+00:00
```

/config/configuration.yaml

```
homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


energy:

sensor:
- platform: fronius_inverter
  ip_address: http://test.my.domain
  power_units: kW
  monitored_conditions:
      - ac_power
      - day_energy
      - year_energy
      - total_energy
```

here is entites 

![image](https://user-images.githubusercontent.com/2538271/144474732-3bfd739d-9b07-44cb-8327-f09d4c18c469.png)
